### ISSUE TITLE
Leadership/Organization and CSS

### ISSUE THREAD

**Issue by samirachamplin** [CNSabers/bscs2016#13]
- Ask and answer questions that prompt teammates to keep the project moving, e.g. how will we do X, who is in charge of X, when should we be done with X, etc.

Xs include: schedule, wireframes, team formation, method of establishing and communicating team goals for each sprint (?)
- Learn about (and apply) the CSS box model

This might take a bit of research, but after I understand why it's designed the way it is, I could draw ideas from it to make my HTML page more user friendly.
- Adopt our more standard way of writing HTML vs. my self-learned, "for my eyes only" style

**Comment by shickey** [comment]
Samira, this sounds like a good start. Now get specific! What do you want to ask and answer questions about? In particular, how can you do that such that it helps move the project forward? On thing to think about is that as the one member of the team who's taken the class before, you have a better sense of the flow of the semester. Some big outstanding to-dos that we need to address soon (that you could step into a leadership role around and making sure happen in a logical order) are:
- Solidifying a project schedule and getting it to the Bakken
- Finalizing wireframes
- Proposing methods for splitting into teams

In terms of CSS stuff, one thing I'm encouraging folks to look into is the idea of the CSS box model. A good goal for this week would be to understand what it is and then be able to apply its principles to your own layout.

And I'll say this to everyone, but go ahead and update the title of this issue to give a descriptive name for your goals this week. That way, we can see everyone's at a glance by clicking on the issues tab!

**Comment by samirachamplin** [comment]
I understand the CSS box model, and should now be ready to apply it! Kincaid's presentation was very helpful – I asked him some questions that helped both the class and me.

My HTML now looks more standard

**Comment by shickey** [comment]
Sound good, Samira. Your HTML looks like it's coming along nicely and you can keep working on that as we move forward. And great job on the wireframes; they're looking good!
