### ISSUE TITLE
April's goals: Coding and styling the sample question page, Leading

### ISSUE THREAD

**Issue by crunchychips** [CNSabers/bscs2016#14]
As a leader for Sprint 1, my goals are to try to push the group to bias toward action, and to be prepared for class meetings. I hope to be as helpful as possible.

My other goals for this sprint:
- Revise my HTML page
- Style the page with CSS in several different ways
- Better my understanding of CSS and HTML
- Respond promptly to slack messages
1. HTML
   - Understand how to use radio buttons
   - Code divs and classes correctly and efficiently
2. CSS
   - Apply the box model to my HTML
   - Style the buttons in the likeness of Buzzfeed quiz buttons
   - Figure out how to style things with the right ratios
3. Leading
   - Promptly make plans for class
   - Keep conversations moving but focused
   - Communicate with class members through slack about homework and plans

**Comment by shickey** [comment]
April, taking the time to focus on leadership stuff is a great goal for this week. In particular, think about: how to plan and schedule the class times (in conjunction with Michael), how to convey that information to the rest of the class in a timely manner, and how to adapt to the needs of the group as things shift over the coming days. To that end, make your goals specific! E.g., what does being prepared for class meetings look like? How can you show that you've done that?

In terms of HTML/CSS stuff, the one thing I'm encouraging everyone to look into is the idea of the CSS box model. This idea is essential for understanding how layout in CSS works so if you are able to understand it and apply its principles toward laying out the content of your HTML page, that would be a big win.

Finally (and I'm saying this to everyone), go ahead and update the title of this issue to reflect your actual goals for this week. This way, we can quickly see what everyone's working on by glancing at the issue tracker in github!

**Comment by crunchychips** [comment]
I accomplished my goals for leading Sprint 1 (besides that very first night) and for HTML. I am familiar with the box model, but my CSS goals still need more work to complete. I along with the UX team finalized a set of wireframes and wireframe screens and sent it off to the Bakken for review, something I had not planned to take on in addition to my CSS and HTML goals.

I'm feeling a lot more comfortable using Slack to communicate now than at the outset of Sprint 1.

**Comment by shickey** [comment]
Thanks, April. You did a great job on the wireframes and your html stuff is looking good. As I said to Michael, the team now really has some forward momentum, which is great, though I encourage you to keep making your voice heard and stepping up when you can (e.g., sending the wireframes to the Bakken).
