### ISSUE TITLE
Sprint 1 - Daniel's Goals

### ISSUE THREAD

**Issue by dajing17** [CNSabers/bscs2016#15]
1. Ask and answer questions regarding the layout of the html pages
2. Revise the html code with the comments from the pull request
3. Learn/Review CSS and look at the CSS box model
4. Finish/Almost finish the CSS for that page 
5. Update myself on the class by reading the HTML guidelines/format, checking slack, and checking github

**Comment by dajing17** [comment]
Overall this week went well and I accomplished a lot. Although I was gone for a math competition, I worked on my html code, learned a lot of new CSS by going over the guidelines, checked slack/github, and asked lots of questions to receive help on my code.

**Comment by shickey** [comment]
Thanks, Daniel. I know this was tricky with you being gone, but are there some specific things that you learned that you can point out from the past sprint? In thinking forward to the future, get specific with your goals! I.e., what will you be able to show/have at the end of the sprint that you didn't at the beginning?

**Comment by dajing17** [comment]
For this particular sprint the only specific thing I can point too is probably just new CSS coding techniques and not much learned about collaboration or teamwork. As my new goals reflect, I will try to broaden the way I engage with the class, such as participating in reviewing code and looking ahead into what we will be doing instead of being pulled by the class. However, for this week, all of what I specifically learned were just CSS coding, such as different css properties and the box model.
