### ISSUE TITLE
Sprint 1 - Michael's Goals: CSS Centering & Classes & Boxes, HTML , Leading

### ISSUE THREAD

**Issue by mthofstadte17** [CNSabers/bscs2016#17]
1. CSS
    a. Learn how to center box elements and text in CSS
    b. Get familiar with tags 
    c. Learn how to use boxes / divs and space them out appropriately
2. HTML
    a. Learn what meta charset does
3. Leading
    a. Have a plan for each class day (coordinated with April and Sean)
    b. Make sure we accomplish what we planned (keep to time constraints)
    c. Have clear homework assignments each night

**Comment by mthofstadte17** [comment]
I accomplished everything! I learned how to put two boxes side-by-side by putting them both in a container div. I now know how to differentiate between id and class and use "#" vs. ".". Kincaid told me what a meta charset is and I was able to make plans with April and Sean each day and night.

**Comment by shickey** [comment]
Nice job this sprint, Michael. I think you stepped up in the leadership role well and by the end of the sprint, the team really had some forward momentum. Some additional questions:
- What _is_ a charset and what does the meta tag do?
- If you were to lead another sprint, what would you do differently?
