### ISSUE TITLE
Spring 1 - Allen's Goals

### ISSUE THREAD

**Issue by allenw16** [CNSabers/bscs2016#18]
1. Revise my HTML code and integrate feedback I got on my pull request
2. Learn CSS and familiarize my self with the box model and our guidelines
3. Submit a pull request for the CSS version of my page by the end of this spring
4. Do GitHub better...

**Comment by shickey** [comment]
Allen, how'd the sprint go for you? Did you accomplish these goals? Add any evidence here in a comment!

**Comment by allenw16** [comment]
I think I accomplished all my goals except for #3 -- although that seems to have morphed into a target goal for the group for Sprint 2 along with the release of Alpha 1.
I revised my HTML code and committed another revision on my initial pull request after reading through the HTML template guidelines that we made. Kincaid looked at it and I got the OK.
I also feel good about the CSS box model -- Kincaid's presentation made a lot of sense, and I'm trying to integrate it into the CSS version of my HTML.
Github-wise, I'm feeling good. I find myself using the web version more than the desktop app (not sure if that's good or bad) but I think I've become better at using it after asking Tristan a few questions.

**Comment by shickey** [comment]
Include links and evidence! What do you know about the box model?

**Comment by allenw16** [comment]
This is my HTML:
https://github.com/CNSabers/bscs2016/pull/7/files

Box Model: The model for coding that considers each HTML element as having its own 'box'. As such, the words/pictures are in a 'content' section, enclosed by a 'padding' section, enclosed by a 'border section', enclosed by a 'content section.' In CSS you can then style the border and change the size of the padding, margin, and content -- padding + margin are transparent so can't style. 
I'm aiming to have a CSS file out by Wednesday night for review, then I can finish revising by Friday. Currently going through a Codecademy Tutorial after I ran into a roadblock on aligning my HTML elements (centering in particular).

**Comment by shickey** [comment]
Great. Thanks, Allen!
