### ISSUE TITLE
Sprint 1 - Connor's Goals (Write, Help Revise, GitHub)

### ISSUE THREAD

**Issue by CNSabers** [CNSabers/bscs2016#19]
1. Finish HTML and CSS for the "Sent Results Confrmation" page
2. Help others to write and revise their code (HTML and CSS) to be more readable and easier to work with going forward.
3. Continue developing familiarity with and knowledge of GitHub
4. Help others improve their understanding of HTML/CSS, GitHub, and the  overall flow of the project and what needs to be done

**Comment by shickey** [comment]
How'd you do on these goals during Sprint 1, Connor? Be sure to reply here with any concrete evidence you have!

**Comment by CNSabers** [comment]
1. I submitted a pull request for my HTML file and started work on CSS, which I completed in Sprint 2
2. I helped people in and out of class (both in person and on Slack) with troubleshooting HTML and CSS
3. Submitted pull request, made a commit
4. See #2, I also contributed to discussions surrounding this in class
